#!/usr/bin/env python3
"""Safe YAML scalar formatting for Docusaurus frontmatter."""

from __future__ import annotations

import json
import re

# Characters that start YAML flow/block structures or aliases
_YAML_START_SPECIAL = frozenset("-?*:!&>|@`#\"'%{},[]")

# Characters that often break unquoted scalars anywhere in the string
_YAML_INLINE_SPECIAL = frozenset(":\n#'\"<>{}[]|&*`")

_YAML_BOOLISH = frozenset(
    {"true", "false", "null", "yes", "no", "on", "off", "~"}
)


DRAFT_GENERATED_NOTE = (
    "<!-- AUTO-GENERATED DRAFT — written by compiler/synthesizer.py to "
    "compiler/temp_output/. Do not edit this file: it is overwritten on every "
    "compile and is not the final wiki page. Edit sources under data/raw/ and "
    "recompile; the final linked page lives in wiki-app/docs/. -->"
)

FINAL_GENERATED_NOTE = (
    "<!-- AUTO-GENERATED — compiled by the LLM Wiki compiler from data/raw/ "
    "sources into compiler/temp_output/, then linked here. Edits to this file "
    "are overwritten on the next compile: edit sources under data/raw/, or "
    "manual cross-links in data/link_overrides.json, instead. -->"
)

_GENERATED_BANNER_RE = re.compile(
    r"^<!--\s*AUTO-GENERATED(?:\sDRAFT)?\b.*?-->\n+", re.DOTALL
)


def strip_generated_banner(body: str) -> str:
    """Remove a previously-inserted AUTO-GENERATED banner comment, if present."""
    return _GENERATED_BANNER_RE.sub("", body, count=1)


def insert_generated_banner(content: str, note: str) -> str:
    """Insert an HTML comment banner right after the YAML frontmatter block."""
    if not content.startswith("---"):
        return f"{note}\n\n{content}"
    parts = content.split("---", 2)
    if len(parts) < 3:
        return f"{note}\n\n{content}"
    body = parts[2].lstrip("\n")
    return f"---{parts[1]}---\n\n{note}\n\n{body}"


def yaml_quote(value: str) -> str:
    """Return a YAML-safe scalar (quoted when needed)."""
    if not value:
        return '""'
    if _needs_yaml_quotes(value):
        return json.dumps(value, ensure_ascii=False)
    return value


def _needs_yaml_quotes(value: str) -> bool:
    stripped = value.lstrip()
    if not stripped:
        return True
    if stripped[0] in _YAML_START_SPECIAL:
        return True
    if value != value.strip():
        return True
    if any(c in value for c in _YAML_INLINE_SPECIAL):
        return True
    if stripped.lower() in _YAML_BOOLISH:
        return True
    if re.fullmatch(r"[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?", stripped):
        return True
    return False
