/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    'index',
    'overview',
    {
      type: 'category',
      label: 'Sources',
      items: [{ type: 'autogenerated', dirName: 'sources' }],
    },
    {
      type: 'category',
      label: 'Entities',
      items: [{ type: 'autogenerated', dirName: 'entities' }],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'Comparisons',
      items: [{ type: 'autogenerated', dirName: 'comparisons' }],
    },
  ],
};

module.exports = sidebars;
